# Generated by Django 4.0 on 2022-01-01 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voterdb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Voter_id', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('voting_status', models.BooleanField(default=False)),
                ('voter_address', models.CharField(blank=True, max_length=45)),
                ('txn_hash', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
